package se.lexicon.market.component.entity;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceFifoGroupingProperty;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.component.entity.AbstractEntityBuilder;
import com.so4it.component.entity.IdEntity;
import se.lexicon.market.component.domain.Money;
import se.lexicon.market.component.domain.MarketPriceType;
import se.lexicon.market.component.domain.Side;

import java.math.BigDecimal;
import java.time.Instant;

/**
 *
 * @author Magnus Poromaa {@literal <mailto:magnus.poromaa@so4it.com/>}
 */
@SpaceClass
public class MarketOrderEntity extends IdEntity<String> {

    @Allowed(value = "Auto generated by GS", types = {Allowed.Type.NULLABLE})
    private String id;

    private String ssn;

    private String orderId;

    private BigDecimal amount;

    private Instant insertionTimestamp;

    // original market
    private String instrument;

    private Integer noOfItems;

    private Money minMaxValue; //Money minValue if SELL, maxValue if BUY;

    private Side side;         // Sell or Buy

    private MarketPriceType marketPriceType; // BUY/SELL at MARKET or LIMITED price

    private String orderBookId;

    // Matching information
    private Integer noOfItemsToMatch;

    private Boolean allItemsMatched;

    private MarketOrderEntity() {
    }

    private MarketOrderEntity(Builder builder) {
        this.id = builder.id;
        this.ssn = Required.notNull(builder.ssn,"ssn",builder.isTemplate());
        this.orderId = Required.notNull(builder.orderId,"orderId",builder.isTemplate());
        this.amount = Required.notNull(builder.amount,"amount",builder.isTemplate());
        this.insertionTimestamp = Required.notNull(builder.insertionTimestamp,"insertionTimestamp",builder.isTemplate());
        this.instrument = Required.notNull(builder.instrument,"instrument",builder.isTemplate());
        this.noOfItems = Required.notNull(builder.noOfItems,"noOfItems",builder.isTemplate());
        this.minMaxValue = Required.notNull(builder.minMaxValue,"minMaxValue",builder.isTemplate());
        this.side = Required.notNull(builder.side,"side",builder.isTemplate());
        this.marketPriceType = Required.notNull(builder.marketPriceType,"marketPriceType",builder.isTemplate());
        this.orderBookId = Required.notNull(builder.orderBookId,"orderBookId",builder.isTemplate());
        this.noOfItemsToMatch = Required.notNull(builder.noOfItemsToMatch,"noOfMatchedItems",builder.isTemplate());
        this.allItemsMatched = Required.notNull(builder.allItemsMatched,"allItemsMatched",builder.isTemplate());
    }

    @Override
    @SpaceId(autoGenerate = true)
    public String getId() {
        return id;
    }

    private void setId(String id) {
        this.id = id;
    }

    public String getSsn() {
        return ssn;
    }

    private void setSsn(String ssn) {
        this.ssn = ssn;
    }

    public String getOrderId() { return orderId; }

    private void setOrderId(String orderId) { this.orderId = orderId; }

    public BigDecimal getAmount() {
        return amount;
    }

    private void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Instant getInsertionTimestamp() {
        return insertionTimestamp;
    }

    private void setInsertionTimestamp(Instant insertionTimestamp) {
        this.insertionTimestamp = insertionTimestamp;
    }

    @SpaceRouting
    @SpaceFifoGroupingProperty
    public String getInstrument() {
        return instrument;
    }

    private void setInstrument(String instrument) {
        this.instrument = instrument;
    }

    public Integer getNoOfItems() {
        return noOfItems;
    }

    private void setNoOfItems(Integer noOfItems) {
        this.noOfItems = noOfItems;
    }

    public Money getMinMaxValue() {
        return minMaxValue;
    }

    private void setMinMaxValue(Money minMaxValue) {
        this.minMaxValue = minMaxValue;
    }

    public Side getSide() {
        return side;
    }

    private void setSide(Side side) {
        this.side = side;
    }

    public MarketPriceType getMarketPriceType() {
        return marketPriceType;
    }

    private void setMarketPriceType(MarketPriceType marketPriceType) {
        this.marketPriceType = marketPriceType;
    }

    public String getOrderBookId() {
        return orderBookId;
    }

    private void setOrderBookId(String orderBookId) {
        this.orderBookId = orderBookId;
    }

    public Integer getNoOfItemsToMatch() {
        return noOfItemsToMatch;
    }

    private void setNoOfItemsToMatch(Integer noOfItemsToMatch) {
        this.noOfItemsToMatch = noOfItemsToMatch;
    }

    public Boolean getAllItemsMatched() {
        return allItemsMatched;
    }

    private void setAllItemsMatched(Boolean allItemsMatched) {
        this.allItemsMatched = allItemsMatched;
    }

    public static Builder builder() {
        return new Builder(false);
    }

    public static Builder templateBuilder() {
        return new Builder(true);
    }


    public static class Builder extends AbstractEntityBuilder<MarketOrderEntity> {

        private String id;

        //The arrangement id of this market balance
        private String ssn;

        private String orderId;

        // Unique id for the posting
        private BigDecimal amount;

        private Instant insertionTimestamp;

        private String instrument;

        private Integer noOfItems;

        private Money minMaxValue; //Money minValue if SELL, maxValue if BUY;

        private Side side;         // Sell or Buy

        private MarketPriceType marketPriceType;

        private String orderBookId;

        private Integer noOfItemsToMatch;

        private Boolean allItemsMatched;

        public Builder(boolean template) {
            super(template);
        }

        public MarketOrderEntity.Builder withId(String id) {
            this.id = id;
            return this;
        }

        public MarketOrderEntity.Builder withSsn(String ssn) {
            this.ssn = ssn;
            return this;
        }

        public MarketOrderEntity.Builder withOrderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

        public MarketOrderEntity.Builder withAmount(BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        public MarketOrderEntity.Builder withInsertionTimestamp(Instant insertionTimestamp) {
            this.insertionTimestamp = insertionTimestamp;
            return this;
        }

        public MarketOrderEntity.Builder withInstrument(String instrument) {
            this.instrument = instrument;
            return this;
        }

        public MarketOrderEntity.Builder withNoOfItems(Integer noOfItems) {
            this.noOfItems = noOfItems;
            return this;
        }

        public MarketOrderEntity.Builder withMinMaxValue(Money minMaxValue) {
            this.minMaxValue = minMaxValue;
            return this;
        }

        public MarketOrderEntity.Builder withSide(Side side) {
            this.side = side;
            return this;
        }

        public MarketOrderEntity.Builder withMarketPriceType(MarketPriceType marketPriceType) {
            this.marketPriceType = marketPriceType;
            return this;
        }

        public MarketOrderEntity.Builder withOrderBookId(String orderBookId) {
            this.orderBookId = orderBookId;
            return this;
        }

        public MarketOrderEntity.Builder withNoOfItemsToMatch(Integer noOfItemsToMatch) {
            this.noOfItemsToMatch = noOfItemsToMatch;
            return this;
        }

        public MarketOrderEntity.Builder withAllItemsMatched(Boolean allItemsMatched) {
            this.allItemsMatched = allItemsMatched;
            return this;
        }

        @Override
        public MarketOrderEntity build() {
            return new MarketOrderEntity(this);
        }
    }
}
